In [2]:
import numpy as np

In [3]:
# creating 2D numpy arrays
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
A.dtype

dtype('int32')

In [5]:
A.ndim

2

In [6]:
A.size

9

In [7]:
A.shape

(3, 3)

In [8]:
B = np.array([[1, 0, 1], [0, 1, 1]])
B

array([[1, 0, 1],
       [0, 1, 1]])

In [9]:
B.shape

(2, 3)

In [11]:
# Indexing
B[1][0]

0

In [12]:
B[0][2]

1

In [15]:
# slicing
A[0][1:3]

array([12, 13])

In [17]:
A[0, 1:]

array([12, 13])

In [18]:
A[:2, 2]

array([13, 23])

In [28]:
x = np.array([[1,0], [0,1]])
y = np.array([[2,1], [1,2]])

In [29]:
# addition
x + y

array([[3, 1],
       [1, 3]])

In [30]:
# subtraction
x - y

array([[-1, -1],
       [-1, -1]])

In [31]:
# multiplication

#Hadamard product
x * y

array([[2, 0],
       [0, 2]])

In [32]:
A = np.array([[0, 1, 1],[1, 0, 1]])
B = np.array([[1, 1], [1, 1], [-1, 1]])

In [33]:
# Dot product or Matrix multiplication
np.dot(A, B)

array([[0, 2],
       [0, 2]])

In [35]:
A.shape

(2, 3)

In [36]:
B.shape

(3, 2)

In [37]:
# Transpose of a matrix
A = np.array([[1,1], [2,2], [3,3]])
A.T

array([[1, 2, 3],
       [1, 2, 3]])